version: '3.8'

services:
  api:
    build: .
    container_name: payflow-api
    image: payflow:latest
    environment:
      - PYTHONPATH=/app
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_SANDBOX=true
      - DB_HOST=db
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    restart: unless-stopped

  # Add additional services like database
  db:
    image: postgres:13-alpine
    container_name: payflow-db
    environment:
      - POSTGRES_USER=${DB_USER:-myuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mypassword}
      - POSTGRES_DB=${DB_NAME:-paypal_transactions}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d paypal_transactions"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 