version: '3.8'

services:
  api:
    build: .
    container_name: paypal-api
    environment:
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_SANDBOX=true
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  # Add additional services like database
  db:
    image: postgres:13
    container_name: paypal-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=paypal_transactions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 